version: "3.7"

services:
  idpdb:
    image: postgres:15.5-bookworm
    restart: always
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=docker